name: Update the package.json file

permissions: 
 contents: write

on:
  push:
    branches:
      - dev

jobs:
  update_package:
    runs-on: ubuntu-latest  
    steps:
      - name: Initial Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set user
        run: |         
         git config --global user.name "Luiscar Castro"
         git config --global user.email "luiscarcastro333@gmail.com"

      - name: Initialize  branch and pull current version
        run: |
         git checkout dev
         git pull origin dev

         
      - name: Send message
        run: echo "Initilazing..."

      - name: Update version
        run: |         
         echo updating...
         npm version patch -m "Version bump to %s"
         git push origin dev
      
        env: 
         GITHUB_TOKEN: ${{secrets.PAT}}
